import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';

// Initialize Google GenAI client (Nano Banana Pro)
const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_API_KEY || '',
});

export async function POST(request: NextRequest) {
  try {
    const { originalImage, maskedImage, markers, style, roomType, additionalPrompt } = await request.json();

    if (!originalImage || !style || !roomType) {
      return NextResponse.json(
        { error: 'Missing required fields: originalImage, style, or roomType' },
        { status: 400 }
      );
    }

    // Helper to format parts for the new SDK
    const formatImagePart = (base64String: string | null) => {
      if (!base64String) return null;
      const base64Content = base64String.split(',')[1] || base64String;
      return {
        inlineData: {
          data: base64Content,
          mimeType: 'image/jpeg',
        },
      };
    };

    const parts: any[] = [];

    // 1. Prompt Construction
    parts.push({
      text: `You are an expert AI Interior Designer.
      Task: Generate a photo-realistic image of the provided room, STAGED with furniture.
      
      CRITICAL:
      1. PRESERVE the ORIGINAL ARCHITECTURE (walls, floor, ceiling, windows) exactly as shown in the "Original Empty Room" image.
      2. GENERATE new furniture items placed into the scene.
      
      Room Type: ${roomType}
      Interior Style: ${style}
      ${additionalPrompt ? `Instructions: ${additionalPrompt}` : ''}`
    });

    parts.push({ text: "IMAGE 1: Original Empty Room (Base Canvas)" });
    parts.push(formatImagePart(originalImage));

    if (maskedImage && markers && markers.length > 0) {
        parts.push({ text: "IMAGE 2: Layout Guide. Use the colored dots to position items." });
        parts.push(formatImagePart(maskedImage));

        for (const marker of markers) {
             const mColor = marker.color;
             const mInstr = marker.instruction || "Furniture item";
             
             let markerText = `\n--- POINT ${mColor} ---\nInstruction: "${mInstr}"`;
             parts.push({ text: markerText });
             
             if (marker.refImage) {
                 parts.push({ text: "Use this reference image for style/shape:" });
                 parts.push(formatImagePart(marker.refImage));
             }
        }
    } else {
        parts.push({ text: "Stage the room naturally with appropriate furniture." });
    }

    // Filter nulls
    const validParts = parts.filter(p => p !== null);

    // 2. Call the Model
    // STRICTLY using "Nano Banana Pro" (gemini-3-pro-image-preview) as requested
    const modelName = 'gemini-3-pro-image-preview'; 
    
    const config = {
      responseModalities: ['IMAGE', 'TEXT'], // Requesting Image!
    };

    console.log(`Calling Nano Banana Pro (${modelName})...`);
    
    const response = await ai.models.generateContent({
      model: modelName, 
      config: config as any,
      contents: [
        {
          role: 'user',
          parts: validParts,
        },
      ],
    });

    // 3. Process Response
    let generatedImageBase64 = null;
    let aiText = "";

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                // Found an image!
                generatedImageBase64 = part.inlineData.data;
            } else if (part.text) {
                aiText += part.text;
            }
        }
    }

    if (!generatedImageBase64) {
        console.warn("No image generated by AI, returning fallback text plan.");
    } else {
        console.log("AI successfully generated an image!");
    }
    
    // If no image, fallback to original to prevent frontend crash, but text will explain
    const finalImage = generatedImageBase64 
        ? `data:image/jpeg;base64,${generatedImageBase64}` 
        : originalImage;

    return NextResponse.json({
      success: true,
      stagedImage: finalImage,
      aiDescription: aiText,
      message: generatedImageBase64 ? "Stage generated successfully!" : "AI analysis complete (No new image generated)",
      style,
      roomType
    });

  } catch (error) {
    console.error('Google GenAI Error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to process with Google AI' },
      { status: 500 }
    );
  }
}
